#!/home/nelhage/sw/bin/node

var fs = require('fs');

if (process.argv[2] === 'config') {
    console.log("graph_title Codesearch stats");
    console.log("graph_vlabel Users");
    console.log("slow.label Slow-query users");
    console.log("slow.draw AREA");
    console.log("fast.label Fast-query users");
    console.log("fast.draw STACK");
    console.log("users.label Total active connections");
    console.log("users.draw LINE1");
    process.exit(0);
}

var data;
try {
    data = JSON.parse(fs.readFileSync('/home/nelhage/codesearch/web/log/stats.json',
                                      'utf8'));
} catch(e) {
    data = {
        clients: 0,
        fast: 0,
        slow: 0
    };
}

console.log("slow.value %d", data.slow);
console.log("fast.value %d", data.fast);
console.log("users.value %d", data.clients);
