#!/bin/sh
set -e;

exec >/tmp/build-codesearch
exec 2>&1

export HOME=$(getent passwd "$(id -un)"  | awk -F: '{print $6}')
export PATH=$PATH:$HOME/sw/bin/

cd "$(dirname "$0")"

(
    cd codesearch/re2
    make -j4
)

(
    cd codesearch
    npm install .
    make -j4
)

