#!/bin/sh

set -e;

export HOME=$(getent passwd "$(id -un)"  | awk -F: '{print $6}')

cd "$(dirname "$0")"

(
    cd gflags
    ./configure  --prefix ~/sw/
    make -j4
    make install
)

(
    mkdir -p libgit2/build
    cd libgit2/build
    cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/sw
    cmake --build . --target install
)

(
    cd json-c
    autoreconf -fvi
    ./configure --prefix ~/sw
    make -j4
    make install
)

(
    cd node
    ./configure  --prefix ~/sw/
    make -j4
    make install
)

(
    cd npm
    ./configure  --prefix=~/sw/
    make -j4
    make install
)

touch sw/.installed
